//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod flashcard;
pub mod flashcard_file;
pub mod flashcard_type;
pub mod flashcard_type_relation;
pub mod permission;
pub mod role;
pub mod role_permission;
pub mod user;
pub mod user_permission;
pub mod user_role;
