//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::flashcard::Entity as Flashcard;
pub use super::flashcard_file::Entity as FlashcardFile;
pub use super::flashcard_type::Entity as FlashcardType;
pub use super::flashcard_type_relation::Entity as FlashcardTypeRelation;
pub use super::mail_template::Entity as MailTemplate;
pub use super::permission::Entity as Permission;
pub use super::role::Entity as Role;
pub use super::role_permission::Entity as RolePermission;
pub use super::user::Entity as User;
pub use super::user_permission::Entity as UserPermission;
pub use super::user_role::Entity as UserRole;
pub use super::user_token::Entity as UserToken;
