//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "flashcard")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
    pub sub_description: Option<String>,
    pub created_date: DateTimeWithTimeZone,
    pub updated_date: DateTimeWithTimeZone,
    pub file_id: i32,
    pub created_by_id: Option<i32>,
    pub updated_by_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::flashcard_file::Entity",
        from = "Column::FileId",
        to = "super::flashcard_file::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FlashcardFile,
    #[sea_orm(has_many = "super::flashcard_type_relation::Entity")]
    FlashcardTypeRelation,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedById",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User2,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UpdatedById",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User1,
}

impl Related<super::flashcard_file::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FlashcardFile.def()
    }
}

impl Related<super::flashcard_type_relation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FlashcardTypeRelation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
