//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::flashcard::Entity as Flashcard;
pub use super::flashcard_type::Entity as FlashcardType;
pub use super::flashcard_type_relation::Entity as FlashcardTypeRelation;
