//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "achievement")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub code: String,
    pub name: String,
    pub description: Option<String>,
    pub icon: Option<String>,
    pub points: i32,
    pub category: Option<String>,
    pub is_actived: bool,
    pub created_date: DateTimeWithTimeZone,
    pub updated_date: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_achievement::Entity")]
    UserAchievement,
}

impl Related<super::user_achievement::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAchievement.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
