//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "game_session")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub game_type_id: i32,
    pub flashcard_type_id: Option<i32>,
    pub score: i32,
    pub max_score: Option<i32>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub accuracy: Option<Decimal>,
    pub time_spent_seconds: i32,
    pub cards_played: i32,
    pub correct_answers: i32,
    pub wrong_answers: i32,
    pub combo_max: i32,
    pub started_at: DateTimeWithTimeZone,
    pub completed_at: Option<DateTimeWithTimeZone>,
    pub created_on: DateTimeWithTimeZone,
    pub updated_on: Option<DateTimeWithTimeZone>,
    pub created_by_id: Option<i32>,
    pub updated_by_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::flashcard_type::Entity",
        from = "Column::FlashcardTypeId",
        to = "super::flashcard_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FlashcardType,
    #[sea_orm(
        belongs_to = "super::game_type::Entity",
        from = "Column::GameTypeId",
        to = "super::game_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GameType,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedById",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User3,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UpdatedById",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User2,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User1,
}

impl Related<super::flashcard_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FlashcardType.def()
    }
}

impl Related<super::game_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
