//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "game_type_flashcard")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "unique")]
    pub game_type_id: i32,
    #[sea_orm(unique_key = "unique")]
    pub flashcard_id: i32,
    pub created_on: DateTimeWithTimeZone,
    pub updated_on: DateTimeWithTimeZone,
    pub created_by_id: Option<i32>,
    pub updated_by_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::flashcard::Entity",
        from = "Column::FlashcardId",
        to = "super::flashcard::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Flashcard,
    #[sea_orm(
        belongs_to = "super::game_type::Entity",
        from = "Column::GameTypeId",
        to = "super::game_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GameType,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedById",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User2,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UpdatedById",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User1,
}

impl Related<super::flashcard::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Flashcard.def()
    }
}

impl Related<super::game_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
