//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_game_progress")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique_key = "idx_user_game_progress_unique")]
    pub user_id: i32,
    #[sea_orm(unique_key = "idx_user_game_progress_unique")]
    pub game_type_id: i32,
    pub current_level: i32,
    pub highest_level: i32,
    pub total_score: i64,
    pub last_played_at: DateTimeWithTimeZone,
    pub created_date: DateTimeWithTimeZone,
    pub updated_date: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::game_type::Entity",
        from = "Column::GameTypeId",
        to = "super::game_type::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GameType,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::game_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameType.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
