//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user_stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub user_id: i32,
    pub total_score: i64,
    pub total_games_played: i32,
    pub total_time_played_seconds: i64,
    pub best_score: i32,
    pub best_combo: i32,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))")]
    pub average_accuracy: Decimal,
    pub current_streak: i32,
    pub best_streak: i32,
    pub last_played_at: Option<DateTimeWithTimeZone>,
    pub updated_date: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
