//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub email: String,
    pub name: String,
    pub display_name: Option<String>,
    pub password_hash: String,
    pub security_stamp: String,
    pub created_by_id: Option<i32>,
    pub created_date: DateTimeWithTimeZone,
    pub updated_date: DateTimeWithTimeZone,
    pub updated_by_id: Option<i32>,
    pub status_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::game_session::Entity")]
    GameSession,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::CreatedById",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef2,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::UpdatedById",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef1,
    #[sea_orm(has_many = "super::user_achievement::Entity")]
    UserAchievement,
    #[sea_orm(has_many = "super::user_game_progress::Entity")]
    UserGameProgress,
    #[sea_orm(has_one = "super::user_stats::Entity")]
    UserStats,
}

impl Related<super::game_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameSession.def()
    }
}

impl Related<super::user_achievement::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAchievement.def()
    }
}

impl Related<super::user_game_progress::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGameProgress.def()
    }
}

impl Related<super::user_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserStats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
