[package]
name = "rex-game-application"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
chrono = "0.4.38"
rex-game-domain = { path = "../domain" }
rex-game-shared = { path = "../shared" }
serde = { version = "1.0", features = ["derive"] }
